#!/bin/sh

ln -s ../../../etc/issue /etc/issue
ln -s ../../../etc/locale.conf /etc/locale.conf
ln -s ../../../etc/makepkg.conf /etc/makepkg.conf
ln -s ../../../etc/mkinitcpio.conf /etc/mkinitcpio.conf
ln -s ../../../etc/pacman.conf /etc/pacman.conf
ln -s ../../../etc/vconsole.conf /etc/vconsole.conf
