#!/bin/sh

ln -sfn ../../../etc/issue /etc/issue
ln -sfn ../../../etc/locale.conf /etc/locale.conf
ln -sfn ../../../etc/makepkg.conf /etc/makepkg.conf
ln -sfn ../../../etc/mkinitcpio.conf /etc/mkinitcpio.conf
ln -sfn ../../../etc/pacman.conf /etc/pacman.conf
ln -sfn ../../../etc/vconsole.conf /etc/vconsole.conf
