#!/bin/sh

ln -sfn ${PWD}/../../../etc/issue /etc/issue
ln -sfn ${PWD}/../../../etc/locale.conf /etc/locale.conf
ln -sfn ${PWD}/../../../etc/makepkg.conf /etc/makepkg.conf
ln -sfn ${PWD}/../../../etc/mkinitcpio.conf /etc/mkinitcpio.conf
ln -sfn ${PWD}/../../../etc/pacman.conf /etc/pacman.conf
ln -sfn ${PWD}/../../../etc/vconsole.conf /etc/vconsole.conf
