#! /bin/sh

sourcesList=(
	"/etc/profile"
	"${HOME}/.profile"
	"${XDG_CONFIG_HOME:-"$HOME/.config"}/bspwm/autostart"
  )

  for file in "${sourcesList[@]}"; do
	[ -r "${file}" ] && . "${file}"
done

gap=10

sxhkd &

bspc monitor -d 壱 弐 参 肆 伍 陸 漆


background=$(xrdb -query | grep "background" | cut -f2 | sed -r 's/#//' | head -n 1)
foreground=$(xrdb -query | grep "foreground" | cut -f2 | sed -r 's/#//' | head -n 1)
color0=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)
color1=$(xrdb -query | grep "color1" | cut -f2 | sed -r 's/#//' | head -n 1)
color2=$(xrdb -query | grep "color2" | cut -f2 | sed -r 's/#//' | head -n 1)
color3=$(xrdb -query | grep "color3" | cut -f2 | sed -r 's/#//' | head -n 1)
color4=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
color5=$(xrdb -query | grep "color5" | cut -f2 | sed -r 's/#//' | head -n 1)
color6=$(xrdb -query | grep "color6" | cut -f2 | sed -r 's/#//' | head -n 1)
color7=$(xrdb -query | grep "color7" | cut -f2 | sed -r 's/#//' | head -n 1)
color8=$(xrdb -query | grep "color8" | cut -f2 | sed -r 's/#//' | head -n 1)

bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc config focused_border_color \#bbbb99
bspc config presel_border_color \#ffff00
bspc config presel_feedback_color "#$color1"

bspc rule -r *:*

bspc rule -a 'Firefox Developer Edition':Navigator state=floating follow=on focus=on
bspc rule -a 'Firefox Developer Edition':Navigator state=floating follow=on focus=on
bspc rule -a 'Firefox Developer Edition':Dialog state=floating

xsetroot -cursor_name left_ptr
