#!/bin/bash

sed --in-place 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+ALL\)/\1/' /etc/sudoers
read -p "choose your root password: " root_password
echo "root:$root_password" | chpasswd
read -p "choose your username: " username
read -p "choose your password: " password
useradd -m -g wheel $username &&
echo "$username:$password" | chpasswd

root_dir="/home/$username/.config/dotfiles/arch/scripts"

pacman -S --noconfirm --needed git
sudo -u $username ./clone_repo &&
ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
hwclock --systohc
$root_dir/etc-symbolic-link &&
locale-gen
read -p "Enter Your hostname: "  hostname
echo "$hostname" | tee /etc/hostname
echo -e "127.0.0.1	localhost\n::1		localhost\n127.0.1.1	$hostname.localdomain	$hostname" | tee /etc/hosts
pacman -Syy
pacman -S --noconfirm --needed aria2 &&
sudo -u $username $root_dir/yay-install &&
sudo -u $username yay -S --noconfirm --needed mkinitcpio-colors-git &&
sudo -u $username yay -S --noconfirm --needed intel-ucode &&
mkinitcpio -P &&
pacman -S --noconfirm --needed refind-efi &&
refind-install
root_partition_uuid=$(findmnt / -o UUID -n)
echo -e "\"Boot using default options\" \"root=UUID=$root_partition_uuid rw add_efi_memmap initrd=intel-ucode.img initrd=initramfs-%v.img\"\n\"Boot using fallback initramfs\" \"root=UUID=$root_partition_uuid rw add_efi_memmap initrd=intel-ucode.img initrd=initramfs-%v-fallback.img\"\n\"Boot to terminal\" \"root=UUID=$root_partition_uuid rw add_efi_memmap initrd=intel-ucode.img initrd=initramfs-%v.img systemd.unit=multi-user.target\"" | tee /boot/refind_linux.conf &&
ls -l /boot
cp $root_dir/../boot/refind.conf /boot/EFI/refind/refind.conf &&
pacman-key --refresh &&
sudo -u $username make -C $root_dir install
