#!/bin/bash

sudo ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
sudo hwclock --systohc
./etc-symbolic-link &&
sudo locale-gen
read -p "Enter Your hostname: "  hostname
sudo echo "$hostname" > /etc/hostname
sudo echo -e "127.0.0.1	localhost\n::1		localhost\n127.0.1.1	$hostname.localdomain	$hostname" > /etc/hosts
sudo pacman -S --noconfirm --needed aria2 &&
./yay-install &&
yay -S --noconfirm --needed mkinitcpio-colors-git
sudo mkinitcpio -P
sudo pacman -S refind-efi &&
sudo refind-install
