#!/bin/bash

ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
hwclock --systohc
./etc-symbolic-link &&
locale-gen
read -p "Enter Your hostname: "  hostname
echo "$hostname" > /etc/hostname
echo -e "127.0.0.1	localhost\n::1		localhost\n127.0.1.1	$hostname.localdomain	$hostname" > /etc/hosts
mkinitcpio -P
pacman -S refind-efi &&
refind-install
