#!/bin/bash

dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME"
git clone --bare https://MeisterTea@github.com/MeisterTea/dotfiles.git $HOME/.dotfiles.git
$dotfiles checkout
$dotfiles config --local status.showUntrackedFiles no
