#!/bin/bash

root_password=$1
username=$2
password=$3

home="/home/$username"
pacman -S --noconfirm --needed git
dotfiles="/usr/bin/git --git-dir=$home/.dotfiles.git/ --work-tree=$home"
git clone --bare https://MeisterTea@github.com/MeisterTea/dotfiles.git $home/.dotfiles.git
$dotfiles checkout
$dotfiles config --local status.showUntrackedFiles no
