#!/bin/sh

sudo ln -sfn ${PWD}/../etc/issue /etc/issue
sudo ln -sfn ${PWD}/../etc/locale.gen /etc/locale.gen
sudo ln -sfn ${PWD}/../etc/locale.conf /etc/locale.conf
sudo ln -sfn ${PWD}/../etc/makepkg.conf /etc/makepkg.conf
sudo ln -sfn ${PWD}/../etc/mkinitcpio.conf /etc/mkinitcpio.conf
sudo ln -sfn ${PWD}/../etc/pacman.conf /etc/pacman.conf
sudo ln -sfn ${PWD}/../etc/vconsole.conf /etc/vconsole.conf
