#!/bin/sh

root_dir=$(dirname $0)

sudo ln -sfn $root_dir/../etc/issue /etc/issue
sudo ln -sfn $root_dir/../etc/locale.gen /etc/locale.gen
sudo ln -sfn $root_dir/../etc/locale.conf /etc/locale.conf
sudo ln -sfn $root_dir/../etc/makepkg.conf /etc/makepkg.conf
sudo ln -sfn $root_dir/../etc/mkinitcpio.conf /etc/mkinitcpio.conf
sudo ln -sfn $root_dir/../etc/pacman.conf /etc/pacman.conf
sudo ln -sfn $root_dir/../etc/vconsole.conf /etc/vconsole.conf
