#!/bin/bash

wget "https://raw.githubusercontent.com/MeisterTea/dotfiles/master/.config/dotfiles/arch/scripts/bootstrap"
wget "https://raw.githubusercontent.com/MeisterTea/dotfiles/master/.config/dotfiles/arch/scripts/bootstrap_chroot"
wget "https://raw.githubusercontent.com/MeisterTea/dotfiles/master/.config/dotfiles/arch/scripts/clone_repo"

./bootstrap
