# default

bootstrap:
	./bootstrap

install:
	./fonts-install
	yay -S --noconfirm --needed - < ./terminal-tools.txt
	yay -S --noconfirm --needed - < ./hack-packages.txt
	yay -S --noconfirm --needed - < ./toys.txt
	./zsh-install
	./neovim-install
	./desktop-environment
	yay -S --noconfirm --needed - < ./thunar-extra.txt
